/**
 * Configuration for slider validation and constraints
 * Centralizes all slider min/max/step values
 */

export const SLIDER_CONFIG = {
  landSize: {
    min: 100,
    max: 2000,
    step: 50,
    default: 600,
    suffix: 'ha',
    tooltip: 'Total farm size in hectares',
  },
  currentLSU: {
    min: 10,
    max: 200,
    step: 1,
    default: 72,
    suffix: 'cattle',
    tooltip: 'Current livestock units',
  },
  targetLSU: {
    min: 10,
    max: 300,
    step: 1,
    default: 110,
    suffix: 'cattle',
    tooltip: 'Target livestock units',
  },
  sekelbosEncroachment: {
    min: 0,
    max: 100,
    step: 1,
    default: 70,
    suffix: '%',
    tooltip: 'Percentage of farm area affected by sekelbos',
  },
  sekelbosCleared: {
    min: 0,
    max: 200,
    step: 10,
    default: 50,
    suffix: 'ha',
    tooltip: 'Hectares of sekelbos cleared per year',
  },
  cattlePerHectare: {
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.2,
    suffix: 'head/ha',
    tooltip: 'Number of cattle per hectare',
  },
  goatsPerHectare: {
    min: 0,
    max: 10,
    step: 0.1,
    default: 1,
    suffix: 'head/ha',
    tooltip: 'Number of goats per hectare',
  },
  pigsPerHectare: {
    min: 0,
    max: 20,
    step: 0.1,
    default: 2,
    suffix: 'head/ha',
    tooltip: 'Number of pigs per hectare',
  },
  chickensPerHectare: {
    min: 0,
    max: 50,
    step: 1,
    default: 10,
    suffix: 'birds/ha',
    tooltip: 'Number of chickens per hectare',
  },
  offtakeRate: {
    min: 0,
    max: 100,
    step: 1,
    suffix: '%',
    tooltip: 'Percentage of herd sold annually',
  },
  offtakeRateHigh: {
    min: 0,
    max: 200,
    step: 5,
    suffix: '%',
    tooltip: 'Percentage of flock/herd sold annually (can exceed 100% for fast-breeding animals)',
  },
  equity: {
    min: 0,
    max: 100,
    step: 1,
    default: 33.33,
    suffix: '%',
    tooltip: 'Equity percentage',
  },
} as const;

/**
 * Range slider configurations
 */
export const RANGE_SLIDER_CONFIG = {
  cattleMarketPrice: {
    min: 5000,
    max: 20000,
    step: 500,
    defaultMin: 8000,
    defaultMax: 12000,
    suffix: 'ZAR',
    tooltip: 'Sale price range per head of cattle',
  },
  goatsMarketPrice: {
    min: 500,
    max: 3000,
    step: 100,
    defaultMin: 1000,
    defaultMax: 1500,
    suffix: 'ZAR',
    tooltip: 'Sale price range per goat',
  },
  pigsMarketPrice: {
    min: 1000,
    max: 4000,
    step: 100,
    defaultMin: 1500,
    defaultMax: 2500,
    suffix: 'ZAR',
    tooltip: 'Sale price range per pig',
  },
  chickensMarketPrice: {
    min: 50,
    max: 200,
    step: 5,
    defaultMin: 80,
    defaultMax: 120,
    suffix: 'ZAR',
    tooltip: 'Sale price range per chicken',
  },
  costPerHectare: {
    min: 0,
    max: 1000,
    step: 50,
    suffix: 'ZAR',
    tooltip: 'Annual cost per hectare',
  },
  costPerAnimal: {
    min: 0,
    max: 2000,
    step: 50,
    suffix: 'ZAR',
    tooltip: 'Annual cost per animal',
  },
  cropsRevenuePerHectare: {
    min: 0,
    max: 10000,
    step: 250,
    defaultMin: 2000,
    defaultMax: 5000,
    suffix: 'ZAR',
    tooltip: 'Annual revenue per hectare of crops',
  },
  cropsCostPerHectare: {
    min: 0,
    max: 5000,
    step: 100,
    defaultMin: 1000,
    defaultMax: 2000,
    suffix: 'ZAR',
    tooltip: 'Annual cost per hectare of crops',
  },
  hansLivestockValue: {
    min: 0,
    max: 200000,
    step: 1000,
    defaultMin: 50000,
    defaultMax: 100000,
    suffix: 'ZAR',
    tooltip: 'Initial value of livestock contribution',
  },
  hansMonthlySalary: {
    min: 0,
    max: 25000,
    step: 500,
    defaultMin: 8000,
    defaultMax: 12000,
    suffix: 'ZAR/month',
    tooltip: 'Monthly salary range',
  },
} as const;
